### ISSUE TITLE
Editing last comment raises error if no comment exists

### ISSUE THREAD

**Issue by sigu** [sigu/intern-fb#4]
![screenshot_20160627_164902](https://cloud.githubusercontent.com/assets/584211/16381865/165a3ac2-3c87-11e6-9148-da17550a9252.png)

With no previous comments associated by a user, an  error is raised trying to access nil object

**Comment by AndyCodez** [comment]
I can work on this.

**Comment by sigu** [comment]
sure @AndyCodez , waiting for a PR on the same
